version: '2'

services:
  nginx:
    image: nginx:latest
    volumes:
      # BIND MOUNTS
      - ./container-nginx.conf:/etc/nginx/nginx.conf
      - ./web:/usr/share/nginx/html
    ports:
      - 8081:80
